"""
Step 5 (Track C): blind, quantitative degeneracy metrics over the Step 4 generation
caches (docs/methodology.md, Track C, Step 5). CPU-only by default; --perplexity
adds a reference-LM pass (GPT-2-large, a *different* model family — scoring Gemma's
steered text with Gemma itself would partially reintroduce the same-forward-pass
dependency this step exists to reduce).

Replaces the manual coherence read in reports/step4_coherence_spotcheck.md with
deterministic metrics computed blind to the output scores. This removes the
*subjectivity* of Step 4's call, not the *same-forward-pass dependency* (the text
was still generated by the steered run that produced the disputed score) — that
residual dependency is Step 6's (CE-Bench) job, out of scope here.

Metrics (per generation, continuation only — prompt prefix stripped first):
  - rep_n = 1 - (unique n-grams / total n-grams), n = 1,2,3 (bigram rep_2 primary)
  - max_run = longest identical-token run / n_tokens
  - nonling = fraction of characters that are markup/bracket/combining-mark noise
    (the degeneration modes observed in Step 4: HTML tags, "{{{", U+0302 spam)
  - ppl (optional): exp(mean per-token NLL) of the continuation under GPT-2-large,
    with the prompt as context but excluded from the loss

Tests (per feature, Mann-Whitney U on per-generation values, rank-biserial effect):
  1. |s| effect:     s=-2 vs s=-10, and s=-2 vs s=-20 (degeneracy should rise)
  2. sign symmetry:  s=+10 vs s=-10 (should NOT differ if coherence tracks |s|)
BH-FDR across the feature x contrast grid per metric.
"""
import argparse
import json
import os
import re
import unicodedata
from collections import defaultdict
from datetime import date

import numpy as np
from scipy.stats import mannwhitneyu

GEN_DIR = "data/generated_texts/gemma_2b"
OUT_JSON = "data/output_scores/step5_degeneracy_metrics.json"
REPORT = "reports/step5_degeneracy_metrics.md"
CANDIDATES_PATH = "data/features/spot_check_reversal_candidates.json"

# condition tag -> (cache basename suffix, signed s)
CONDITIONS = {"+10": ("10", 10), "-2": ("neg2", -2), "-10": ("neg10", -10), "-20": ("neg20", -20)}

# Index-aligned with the 50 hard-coded generation prefixes in src/steer.py.
PREFIXES = ["Findings show that", "I once heard that", "Then the man said:", "I believe that",
            "The news mentioned", "She saw a", "It is observed that", "Studies indicate that",
            "According to reports,", "Research suggests that", "It has been noted that", "I remember when",
            "It all started when", "The legend goes that", "If I recall correctly,", "People often say that",
            "Once upon a time,", "It’s no surprise that", "Have you ever noticed that", "I couldn't believe when",
            "The first thing I heard was", "Let me tell you a story about", "Someone once told me that",
            "It might sound strange, but", "They always warned me that", "Nobody expected that", "Funny thing is,",
            "I never thought I'd say this, but", "What surprised me most was", "The other day, I overheard that",
            "Back in the day,", "You won’t believe what happened when", "A friend of mine once said,",
            "I just found out that", "It's been a long time since", "In my experience,",
            "The craziest part was when", "If you think about it,", "I was shocked to learn that",
            "For some reason,", "I can’t help but wonder if", "It makes sense that",
            "At first, I didn't believe that", "That reminds me of the time when", "It all comes down to",
            "One time, I saw that", "I was just thinking about how", "Imagine a world where",
            "They never expected that", "I always knew that"]

# Deterministic regex tokenizer: words, or any single non-space symbol (so "<strong>"
# splits into "<", "strong", ">" and tag spam registers as token repetition).
TOKEN_RE = re.compile(r"\w+|[^\w\s]")

# Characters counted as non-linguistic noise: markup/bracket symbols observed in the
# degenerate generations, plus combining marks / format chars via unicodedata below.
NOISE_CHARS = set("<>{}[]|\\^~_=")


def strip_prefix(text, idx):
    """Remove the generation prompt prefix; continuation only."""
    pref = PREFIXES[idx]
    if text.startswith(pref):
        return text[len(pref):]
    # order mismatch fallback: longest matching known prefix
    matches = [p for p in PREFIXES if text.startswith(p)]
    if matches:
        return text[len(max(matches, key=len)):]
    return text  # no known prefix; score the whole string


def tokenize(text):
    return TOKEN_RE.findall(text)


def rep_rate(tokens, n):
    grams = [tuple(tokens[i:i + n]) for i in range(len(tokens) - n + 1)]
    if not grams:
        return np.nan
    return 1.0 - len(set(grams)) / len(grams)


def max_run_frac(tokens):
    if not tokens:
        return np.nan
    best = run = 1
    for a, b in zip(tokens, tokens[1:]):
        run = run + 1 if a == b else 1
        best = max(best, run)
    return best / len(tokens)


def nonling_frac(text):
    if not text:
        return np.nan
    n = sum(1 for c in text
            if c in NOISE_CHARS or unicodedata.category(c) in ("Mn", "Cf", "So"))
    return n / len(text)


def text_metrics(cont):
    toks = tokenize(cont)
    return {
        "rep_1": rep_rate(toks, 1),
        "rep_2": rep_rate(toks, 2),
        "rep_3": rep_rate(toks, 3),
        "max_run": max_run_frac(toks),
        "nonling": nonling_frac(cont),
        "n_tokens": len(toks),
    }


def add_perplexity(records, device):
    """Mean-NLL perplexity of each continuation under GPT-2-large (prompt as
    context, excluded from the loss). Mutates records in place."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    name = "gpt2-large"
    tok = AutoTokenizer.from_pretrained(name)
    model = AutoModelForCausalLM.from_pretrained(name).to(device).eval()
    with torch.no_grad():
        for r in records:
            cont = r["continuation"]
            if not cont.strip():
                r["ppl"] = np.nan
                continue
            pref_ids = tok(PREFIXES[r["gen_idx"]]).input_ids
            full_ids = tok(PREFIXES[r["gen_idx"]] + cont).input_ids
            ids = torch.tensor([full_ids], device=device)
            logits = model(ids).logits[0, :-1]
            targets = ids[0, 1:]
            nll = torch.nn.functional.cross_entropy(logits, targets, reduction="none")
            cont_nll = nll[max(len(pref_ids) - 1, 0):]  # loss on continuation tokens only
            r["ppl"] = float(torch.exp(cont_nll.mean())) if len(cont_nll) else np.nan
    return name


def bh_fdr(pvals):
    """Benjamini-Hochberg FDR-adjusted p-values (nan-safe)."""
    p = np.asarray(pvals, dtype=float)
    out = np.full_like(p, np.nan)
    idx = np.where(~np.isnan(p))[0]
    m = len(idx)
    if m == 0:
        return out
    order = idx[np.argsort(p[idx])]
    adj = p[order] * m / np.arange(1, m + 1)
    adj = np.minimum.accumulate(adj[::-1])[::-1]
    out[order] = np.clip(adj, 0, 1)
    return out


def mwu(a, b):
    """Two-sided Mann-Whitney U p-value and rank-biserial effect (b>a positive)."""
    a = np.asarray(a)[~np.isnan(a)]
    b = np.asarray(b)[~np.isnan(b)]
    if len(a) < 2 or len(b) < 2:
        return np.nan, np.nan
    u, p = mannwhitneyu(b, a, alternative="two-sided")
    rb = 2 * u / (len(a) * len(b)) - 1
    return p, rb


def med_iqr(vals):
    v = np.asarray(vals, dtype=float)
    v = v[~np.isnan(v)]
    if len(v) == 0:
        return "—"
    q1, q3 = np.percentile(v, [25, 75])
    return f"{np.median(v):.3f} [{q1:.3f}, {q3:.3f}]"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--perplexity", action="store_true",
                    help="also score continuations with GPT-2-large (needs torch/transformers)")
    ap.add_argument("--device", default=None, help="torch device for --perplexity (default: auto)")
    args = ap.parse_args()

    with open(CANDIDATES_PATH) as f:
        candidates = json.load(f)
    feat_keys = [f"{lyr}_{feat}" for lyr, feats in candidates.items() for feat in feats]

    # ---- per-generation metrics (blind: no score cache is loaded here) ----
    records = []
    for cond, (suffix, s) in CONDITIONS.items():
        path = os.path.join(GEN_DIR, f"gemma2_2b_generations_cache_{suffix}_0.json")
        with open(path) as f:
            cache = json.load(f)
        for key in feat_keys:
            for i, text in enumerate(cache[key]):
                cont = strip_prefix(text, i)
                rec = {"feature": key, "cond": cond, "s": s, "gen_idx": i,
                       "continuation": cont, **text_metrics(cont)}
                records.append(rec)

    ppl_model = None
    if args.perplexity:
        try:
            import torch
            device = args.device or ("cuda" if torch.cuda.is_available() else "cpu")
            ppl_model = add_perplexity(records, device)
        except ImportError as e:
            print(f"[warn] --perplexity skipped (missing dependency: {e})")

    metrics = ["rep_1", "rep_2", "rep_3", "max_run", "nonling"] + (["ppl"] if ppl_model else [])
    by_cell = defaultdict(list)  # (feature, cond) -> records
    for r in records:
        by_cell[(r["feature"], r["cond"])].append(r)

    def vals(key, cond, metric):
        return [r[metric] for r in by_cell[(key, cond)]]

    # ---- contrasts + FDR (per metric, across the feature x contrast grid) ----
    contrasts = [("-2", "-10", "|s| effect"), ("-2", "-20", "|s| effect"),
                 ("+10", "-10", "sign symmetry")]
    tests = {m: [] for m in metrics}
    for m in metrics:
        for key in feat_keys:
            for ca, cb, label in contrasts:
                p, rb = mwu(vals(key, ca, m), vals(key, cb, m))
                tests[m].append({"feature": key, "contrast": f"{ca} vs {cb}",
                                 "label": label, "p": p, "rb": rb})
        pf = bh_fdr([t["p"] for t in tests[m]])
        for t, q in zip(tests[m], pf):
            t["p_fdr"] = float(q) if not np.isnan(q) else None

    # ---- report ----
    cond_order = ["+10", "-2", "-10", "-20"]
    lines = [
        "*AI-assistance disclosure: see [`AI_ASSISTANCE.md`](./AI_ASSISTANCE.md).*", "",
        "# Step 5: Quantitative Degeneracy Metrics on the Step 4 Generations", "",
        "## Summary", "", "*(placeholder — write after reading the tables below)*", "",
        "**Method.** Blind, deterministic metrics over the cached generations",
        f"(`{GEN_DIR}/gemma2_2b_generations_cache_{{10,neg2,neg10,neg20}}_0.json`;",
        "4 candidate features x 4 magnitudes x 50 generations). Prompt prefixes",
        "(the 50 hard-coded in `src/steer.py`) stripped; metrics on continuations only.",
        "Tokenizer: deterministic regex (`\\w+|[^\\w\\s]` — punctuation/markup symbols",
        "are single tokens, so tag spam registers as repetition).",
        f"Reference LM for perplexity: {ppl_model or 'not run (use --perplexity on the GPU box)'}.",
        "", "**Caveat (per docs/methodology.md Track C):** this removes the *subjectivity*",
        "of Step 4's manual read, not the *same-forward-pass dependency* — the text was",
        "still generated by the steered run that produced the disputed score. Independent",
        "corroboration is Step 6 (CE-Bench).", "",
        "Metric definitions: `rep_n` = 1 − unique/total n-grams (higher = more repetitive);",
        "`max_run` = longest identical-token run / n_tokens; `nonling` = fraction of",
        "markup/bracket/combining-mark characters; `ppl` = continuation perplexity under",
        "the reference LM (prompt as context, excluded from loss). Cells: median [IQR], n=50.", "",
    ]

    for m in metrics + ["n_tokens"]:
        lines += [f"## {m} per feature x condition", ""]
        if m == "n_tokens":
            lines += ["Continuation length (tokens). **Read the repetition tables against this",
                      "one:** a near-zero rep_n on a very short continuation (e.g. a garbled",
                      "fragment that truncates early) is degeneracy-by-brevity, not fluency.", ""]
        lines += [
                  "| feature | " + " | ".join(f"s={c}" for c in cond_order) + " |",
                  "|---|" + "---|" * len(cond_order)]
        for key in feat_keys:
            row = " | ".join(med_iqr(vals(key, c, m)) for c in cond_order)
            lines.append(f"| `{key}` | {row} |")
        lines.append("")

    lines += ["## Hypothesis tests", "",
              "Mann-Whitney U (two-sided) per feature and contrast; `rb` = rank-biserial",
              "effect size, positive = second condition more degenerate (higher metric).",
              "`p_fdr` = BH across the feature x contrast grid within each metric.",
              "Interpretation: the *|s| effect* rows should be significant with rb > 0;",
              "the *sign symmetry* rows (+10 vs −10) should show small |rb| — but treat a",
              "non-significant p there as absence-of-evidence, not equivalence, unless",
              "|rb| is also small.", ""]
    for m in metrics:
        lines += [f"### {m}", "",
                  "| feature | contrast | claim | rb | p | p_fdr |", "|---|---|---|---|---|---|"]
        for t in tests[m]:
            p = "—" if np.isnan(t["p"]) else f"{t['p']:.2e}"
            pf = "—" if t["p_fdr"] is None else f"{t['p_fdr']:.2e}"
            rb = "—" if np.isnan(t["rb"]) else f"{t['rb']:+.2f}"
            lines.append(f"| `{t['feature']}` | {t['contrast']} | {t['label']} | {rb} | {p} | {pf} |")
        lines.append("")

    # ---- 14_6669 spotlight (the only section that touches score caches) ----
    lines += ["## Spotlight: `14_6669` monotonicity", "",
              "Step 1 flagged `14_6669` as the single monotonic-reversal candidate (output",
              "score rising across −2/−10/−20); Step 4's manual read attributed that rise to",
              "degenerate generation. Blind check: does degeneracy also rise monotonically?", ""]
    spot = "14_6669"
    lines += ["| s | " + " | ".join(metrics) + " | output score |",
              "|---|" + "---|" * (len(metrics) + 1)]
    score_caches = {"-2": "gemma2_2b_suppress_amp2.json", "-10": "gemma2_2b_suppress.json",
                    "-20": "gemma2_2b_suppress_amp20.json", "+10": "gemma2_2b_amplify.json"}
    for c in cond_order:
        sc = "—"
        cache = None
        path = os.path.join("data/output_scores", score_caches[c])
        if os.path.exists(path):
            with open(path) as f:
                cache = json.load(f)
            cache = cache.get("scores", cache)  # flat or {meta, scores}
        if cache and spot in cache:
            v = cache[spot]
            sc = f"{np.mean(v):.4f}" if isinstance(v, list) else f"{v:.4f}"
        row = " | ".join(med_iqr(vals(spot, c, m)).split(" [")[0] for m in metrics)
        lines.append(f"| {c} | {row} | {sc} |")
    lines += ["", "(medians only; output score shown for context — the metrics above were",
              "computed without loading it.)", ""]

    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as f:
        f.write("\n".join(lines))

    # ---- raw metrics JSON ({meta, ...} cache style; drop text to keep it small) ----
    meta = {"script": "src/analyze_generation_degeneracy.py", "date": str(date.today()),
            "conditions": {c: s for c, (_, s) in CONDITIONS.items()},
            "tokenizer": "regex \\w+|[^\\w\\s]", "ppl_model": ppl_model,
            "candidates": feat_keys, "n_generations_per_cell": 50}
    out_records = [{k: (None if isinstance(v, float) and np.isnan(v) else v)
                    for k, v in r.items() if k != "continuation"} for r in records]
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump({"meta": meta, "metrics": out_records, "tests": tests}, f, indent=1, default=float)

    print(f"wrote {REPORT} and {OUT_JSON} ({len(records)} generations scored)")


if __name__ == "__main__":
    main()
